### ISSUE TITLE
Implement Jenkins deployment script for apps

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/jenkins#2]
Depends on cibr-qcri/jenkins#1

- Make sure to use a different port to run each app (dizzy/toshi/kansa) and ask Tasos for proper proxy mapping if needed. Dizzy and Toshi already have these mappings.
- DNS entry for kansa.cibr.qcri.org
- Webapp and API deployment Jenkins jobs for the three apps
- For all apps, set all secrets, api keys, passwords from docker-compose yaml file to use Jenkins secrets (can read them as env variables, and Jenkins should set them at pre/build time).
- Use Jenkins secrets for application secrets

**Comment by sajithaliyanage** [comment]
Completed In: https://github.com/cibr-qcri/jenkins
